AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  HttpApi:
    Auth:
      EnableIamAuthorizer: true

Parameters:
  UserPoolName:
    Type: String
    Default: MyUserPool
  IdentityPoolName:
    Type: String
    Default: MyIdentityPool

Resources:
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /sam-app/ops
      RetentionInDays: 7

  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Ref UserPoolName
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: true
      LambdaConfig:
        PostConfirmation: !GetAtt TopicSubscriptionsFunction.Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailSubject: "Welcome to My App! Please verify your email"
        EmailMessage: |
          Hello, {username}. Please verify your email address by clicking the link below: {####}

  AdminGroup:
    Type: AWS::Cognito::UserPoolGroup
    Properties:
      GroupName: Admins
      UserPoolId: !Ref CognitoUserPool


  AdminUser:
    Type: AWS::Cognito::UserPoolUser
    Properties:
      DesiredDeliveryMediums:
        - EMAIL
      UserAttributes:
        - Name: email
          Value: kofi.gyawu@amalitech.com
      Username: kofi.gyawu@amalitech.com
      UserPoolId: !Ref CognitoUserPool

  AdminClosedNotifications:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ClosedTaskNotificationTopic
      Endpoint: !Ref AdminUser
      Protocol: email

  AdminCompleteNotifications:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref TaskCompleteNotificationTopic
      Endpoint: !Ref AdminUser
      Protocol: email


  AddUserAdminToAdminGroup:
    Type: AWS::Cognito::UserPoolUserToGroupAttachment
    Properties:
      UserPoolId: !Ref CognitoUserPool
      GroupName: !Ref AdminGroup
      Username: !Ref AdminUser


  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: sam-app-test-123
      UserPoolId: !Ref CognitoUserPool

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref CognitoUserPool
      ClientName: app-client
      GenerateSecret: false
      AllowedOAuthFlows:
        - implicit
      AllowedOAuthScopes:
        - email
        - openid
        - profile
      AllowedOAuthFlowsUserPoolClient: true
      SupportedIdentityProviders:
        - COGNITO
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      CallbackURLs:
        - http://localhost:3000/callback

  CognitoIdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      IdentityPoolName: !Ref IdentityPoolName
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId: !Ref UserPoolClient
          ProviderName: !GetAtt CognitoUserPool.ProviderName

  AuthenticatedRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
      Policies:
        - PolicyName: AuthenticatedPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'execute-api:Invoke'
                Resource:
                  - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessHttpApi}/*/GET/task
                  - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessHttpApi}/*/POST/task/comment
                  - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessHttpApi}/*/GET/task/comment
                  - !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessHttpApi}/*/PATCH/task/complete

  # IAM role for admin users
  AdminRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                'cognito-identity.amazonaws.com:aud': !Ref CognitoIdentityPool
              'ForAnyValue:StringLike':
                'cognito-identity.amazonaws.com:amr': authenticated
                'cognito-identity.amazonaws.com:groups': Admins
      Policies:
        - PolicyName: AdminPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'execute-api:Invoke'
                Resource: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ServerlessHttpApi}/*/*/*

  IdentityPoolRoles:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref CognitoIdentityPool
      Roles:
        authenticated: !GetAtt AuthenticatedRole.Arn
      RoleMappings:
        "userpool":
          Type: Token
          AmbiguousRoleResolution: AuthenticatedRole
          IdentityProvider: !Sub ${CognitoUserPool.ProviderName}:${UserPoolClient}
          RulesConfiguration:
            Rules:
              - Claim: "cognito:groups"
                MatchType: Contains
                Value: "Admins"
                RoleARN: !GetAtt AdminRole.Arn

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getCredentials
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:GetId
                - cognito-idp:GetCredentialsForIdentity
              Resource: arn:aws:cognito-identity:eu-central-1:122610498016:identitypool/eu-central-1:e8c0e26f-dbdc-4892-b742-f5895ca4766f
        - AWSLambdaBasicExecutionRole
        - CloudWatchLambdaInsightsExecutionRolePolicy
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          SPRING_CLOUD_DEFINITION: getCredentials
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_CLIENT_ID: !Ref UserPoolClient
          IDENTITY_POOL_ID: !Ref CognitoIdentityPool
          LOG_LEVEL: INFO
      Events:
        Api:
          Type: HttpApi
          Properties:
            Path: /auth
            Method: POST


  UserService:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: registerUser
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - cognito-idp:AdminCreateUser
              Resource: !GetAtt CognitoUserPool.Arn
        - AWSLambdaBasicExecutionRole
        - CloudWatchLambdaInsightsExecutionRolePolicy
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          SPRING_CLOUD_DEFINITION: registerUser
          COGNITO_USER_POOL_ID: !Ref CognitoUserPool
          COGNITO_CLIENT_ID: !Ref UserPoolClient
          LOG_LEVEL: INFO
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /signup
            Method: POST

  TopicSubscriptionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: subscribeUser
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSLambdaBasicExecutionRole
        - CloudWatchLambdaInsightsExecutionRolePolicy
        - Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Ref TopicSubscriptionStateMachine
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          SPRING_CLOUD_DEFINITION: subscribeUser
          STATE_MACHINE_ARN: !Ref TopicSubscriptionStateMachine
          TaskAssignmentNotificationTopic: !Ref TaskAssignmentNotificationTopic
          TaskDeadlineNotificationTopic: !Ref TaskDeadlineNotificationTopic
          ClosedTaskNotificationTopic: !Ref ClosedTaskNotificationTopic
          ReopenedTasksNotificationTopic: !Ref ReopenedTasksNotificationTopic

  TopicSubscriptionStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: workflow.asl.json
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - sns:Subscribe
                - sns:GetTopicAttributes
              Resource:
                - !Ref TaskAssignmentNotificationTopic
                - !Ref TaskDeadlineNotificationTopic
                - !Ref ClosedTaskNotificationTopic
                - !Ref ReopenedTasksNotificationTopic

  TaskAssignmentNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TaskAssignmentNotificationTopic
      Tags:
        - Key: "Stack"
          Value: !Sub "${AWS::StackName}"

  TaskDeadlineNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TaskDeadlineNotificationTopic
      Tags:
        - Key: "Stack"
          Value: !Sub "${AWS::StackName}"

  ClosedTaskNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ClosedTaskNotificationTopic
      Tags:
        - Key: "Stack"
          Value: !Sub "${AWS::StackName}"

  ReopenedTasksNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: ReopenedTasksNotificationTopic
      Tags:
        - Key: "Stack"
          Value: !Sub "${AWS::StackName}"

  TaskCompleteNotificationTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: TaskCompleteNotificationTopic
      Tags:
        - Key: "Stack"
          Value: !Sub "${AWS::StackName}"

# Task Service resources
  TaskQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: TaskQueue

  TaskTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: TaskTable
      PrimaryKey:
        Name: id
        Type: Number

  CommentTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: CommentTable
      PrimaryKey:
        Name: id
        Type: Number

#add authorizer
  CreateTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: createTask
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          TASK_TABLE: !Ref TaskTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /task
            Method: POST

  ListTasks:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: listTasks
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          TASK_TABLE: !Ref TaskTable
          COMMENT_TABLE: !Ref CommentTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /task
            Method: GET

  CompleteTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: completeTask
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          TASK_TABLE: !Ref TaskTable
          COMMENT_TABLE: !Ref CommentTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /task/complete
            Method: PATCH

  ReassignTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: reassignTask
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          TASK_TABLE: !Ref TaskTable
          COMMENT_TABLE: !Ref CommentTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /task/reassign
            Method: PATCH

  reopenTask:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: reopenTask
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          TASK_TABLE: !Ref TaskTable
          COMMENT_TABLE: !Ref CommentTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /task/reopen
            Method: PATCH

  NotificationLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: notifyUsers
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Tracing: Active
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaSQSQueueExecutionRole
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          SPRING_CLOUD_DEFINITION: subscribeUser
          STATE_MACHINE_ARN: !Ref TopicSubscriptionStateMachine
          TaskAssignmentNotificationTopic: !Ref TaskAssignmentNotificationTopic
          TaskDeadlineNotificationTopic: !Ref TaskDeadlineNotificationTopic
          ClosedTaskNotificationTopic: !Ref ClosedTaskNotificationTopic
          ReopenedTasksNotificationTopic: !Ref ReopenedTasksNotificationTopic
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TaskQueue.Arn
            BatchSize: 1

#
#      Events:
#        Api:
#          Type: HttpApi
#          Properties:
#            Auth:
#              Authorizer: AWS_IAM
#            Path: /signup
#            Method: POST

  CheckDeadlines:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: checkDeadlines
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref TaskTable
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          TASK_TABLE: !Ref TaskTable
          COMMENT_TABLE: !Ref CommentTable
      Events:
        Schedule:
          Type: ScheduleV2
          Properties:
            ScheduleExpression: 'rate(30 minutes)'
            Name: CheckExpiredDeadlines



  MakeComment:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: comment
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref CommentTable
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          TASK_TABLE: !Ref TaskTable
          COMMENT_TABLE: !Ref CommentTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /task/comment
            Method: POST

  GetComments:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: getComments
      Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
      Runtime: java17
      CodeUri: .
      MemorySize: 512
      Timeout: 30
      Policies:
        - AWSLambdaBasicExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Ref CommentTable
      Environment:
        Variables:
          MAIN_CLASS: com.awsmicroservices.userservice.UserserviceApplication
          TASK_TABLE: !Ref TaskTable
          COMMENT_TABLE: !Ref CommentTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            Auth:
              Authorizer: AWS_IAM
            Path: /task/comment
            Method: GET

Outputs:
  UserApi:
    Description: API Gateway endpoint URL
    Value: !Sub https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/
  UserService:
    Description: Lambda Function ARN
    Value: !GetAtt UserService.Arn
  CognitoDomain:
    Description: Url for cognito hosted login pages
    Value: !Sub https://${UserPoolDomain}.auth.${AWS::Region}.amazoncognito.com/login?client_id=${UserPoolClient}&redirect_uri=http://localhost:3000/callback&response_type=token
